export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';

export const FETCH_ROOM_START = 'FETCH_ROOM_START';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';
export const FETCH_ROOM_END = 'FETCH_ROOM_END';

export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const FETCH_MESSAGES_END = 'FETCH_MESSAGES_END';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_END = 'FETCH_USERS_END';

export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';
export const FETCH_CURRENT_USER_END = 'FETCH_CURRENT_USER_END';

export const UPDATE_CURRENT_USER_START = 'UPDATE_CURRENT_USER_START';
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE';
export const UPDATE_CURRENT_USER_END = 'UPDATE_CURRENT_USER_END';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_END = 'SIGN_UP_END';

export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_END = 'SIGN_IN_END';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const READ_MESSAGES = 'READ_MESSAGES';
