export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS = 'FETCH_ROOM_SUCCESS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
